name: CI for my-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add error checking for Docker
      - name: Check Docker status
        run: |
          if ! docker info > /dev/null 2>&1; then
            echo "Docker is not running or accessible"
            exit 1
          fi
          docker --version

      - name: Check Docker Compose
        run: |
          docker-compose --version

      - name: Build services with debug output
        run: |
          docker-compose build --no-cache --progress=plain

      - name: Start Services with logs
        run: |
          docker-compose up -d
          docker-compose ps
          docker-compose logs

      # Modified connectivity tests with better error handling
      - name: Test frontend-to-backend connectivity
        run: |
          sleep 10  # Give containers time to fully start
          if ! docker-compose ps | grep -q "frontend.*Up"; then
            echo "Frontend container is not running"
            docker-compose logs frontend
            exit 1
          fi
          if ! docker-compose ps | grep -q "backend.*Up"; then
            echo "Backend container is not running"
            docker-compose logs backend
            exit 1
          fi
          docker-compose exec -T frontend ping -c 2 backend || exit 1

      - name: Cleanup
        if: always()
        run: |
          docker-compose down -v